# Generated by Django 4.1.3 on 2022-12-01 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="is_favourite",
            new_name="favourite_by",
        ),
    ]
